export interface FilterDef {
  id: string;
  label: string;
  type: 'slider' | 'toggle' | 'select' | 'file';
  min?: number;
  max?: number;
  step?: number;
  defaultValue?: number;
  options?: string[];
}

export interface FilterCategory {
  id: string;
  label: string;
  filters: FilterDef[];
}

export const FILTER_CATEGORIES: FilterCategory[] = [
  {
    id: 'essentials',
    label: 'Essentials',
    filters: [
      { id: 'brightness', label: 'Brightness', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'contrast', label: 'Contrast', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'exposure', label: 'Exposure', type: 'slider', min: -3, max: 3, step: 0.01, defaultValue: 0 },
      { id: 'gamma', label: 'Gamma', type: 'slider', min: 0.1, max: 3, step: 0.01, defaultValue: 1 },
      { id: 'saturation', label: 'Saturation', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'vibrance', label: 'Vibrance', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'hueShift', label: 'Hue Shift', type: 'slider', min: -180, max: 180, step: 1, defaultValue: 0 },
      { id: 'temperature', label: 'Temperature', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'tint', label: 'Tint', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'whiteBalance', label: 'White Balance', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'blacks', label: 'Blacks', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'whites', label: 'Whites', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'shadows', label: 'Shadows', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'highlights', label: 'Highlights', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'midtones', label: 'Midtones', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'lift', label: 'Lift', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'gammaColor', label: 'Gamma (Color)', type: 'slider', min: 0.1, max: 3, step: 0.01, defaultValue: 1 },
      { id: 'gain', label: 'Gain', type: 'slider', min: 0, max: 3, step: 0.01, defaultValue: 1 },
      { id: 'curvesRGB', label: 'Curves (RGB)', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'curvesR', label: 'Curves (R)', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'curvesG', label: 'Curves (G)', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'curvesB', label: 'Curves (B)', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'levels', label: 'Levels', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'histogramEq', label: 'Histogram Equalization', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'autoLevels', label: 'Auto Levels', type: 'toggle', defaultValue: 0 },
      { id: 'autoContrast', label: 'Auto Contrast', type: 'toggle', defaultValue: 0 },
      { id: 'autoWhiteBalance', label: 'Auto White Balance', type: 'toggle', defaultValue: 0 },
    ],
  },
  {
    id: 'colorStylization',
    label: 'Color Stylization',
    filters: [
      { id: 'colorize', label: 'Colorize', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'duotone', label: 'Duotone', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'tritone', label: 'Tritone', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'gradientMap', label: 'Gradient Map', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'posterize', label: 'Posterize', type: 'slider', min: 2, max: 32, step: 1, defaultValue: 8 },
      { id: 'solarize', label: 'Solarize', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'threshold', label: 'Threshold', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0.5 },
      { id: 'invert', label: 'Invert', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'negative', label: 'Negative', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'sepia', label: 'Sepia', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'monochrome', label: 'Monochrome', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'bwMixer', label: 'Black & White Mixer', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'selectiveColor', label: 'Selective Color', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'replaceColor', label: 'Replace Color', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'channelMixer', label: 'Channel Mixer', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'colorBalance', label: 'Color Balance', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'splitToning', label: 'Split Toning', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'lutLoader', label: 'LUT Loader (.cube)', type: 'file', defaultValue: 0 },
      { id: 'falseColor', label: 'False Color', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'thermalVision', label: 'Thermal Vision', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'infrared', label: 'Infrared', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'blur',
    label: 'Blur',
    filters: [
      { id: 'gaussianBlur', label: 'Gaussian Blur', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'boxBlur', label: 'Box Blur', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'kawaseBlur', label: 'Kawase Blur', type: 'slider', min: 0, max: 20, step: 1, defaultValue: 0 },
      { id: 'directionalBlur', label: 'Directional Blur', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'radialBlur', label: 'Radial Blur', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'zoomBlur', label: 'Zoom Blur', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'lensBlur', label: 'Lens Blur', type: 'slider', min: 0, max: 30, step: 0.1, defaultValue: 0 },
      { id: 'motionBlur', label: 'Motion Blur', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'tiltShift', label: 'Tilt Shift', type: 'slider', min: 0, max: 30, step: 0.1, defaultValue: 0 },
      { id: 'surfaceBlur', label: 'Surface Blur', type: 'slider', min: 0, max: 30, step: 0.1, defaultValue: 0 },
      { id: 'smartBlur', label: 'Smart Blur', type: 'slider', min: 0, max: 30, step: 0.1, defaultValue: 0 },
      { id: 'bilateralBlur', label: 'Bilateral Blur', type: 'slider', min: 0, max: 30, step: 0.1, defaultValue: 0 },
      { id: 'bokehBlur', label: 'Bokeh Blur', type: 'slider', min: 0, max: 30, step: 0.1, defaultValue: 0 },
    ],
  },
  {
    id: 'sharpen',
    label: 'Sharpen',
    filters: [
      { id: 'sharpen', label: 'Sharpen', type: 'slider', min: 0, max: 5, step: 0.01, defaultValue: 0 },
      { id: 'unsharpMask', label: 'Unsharp Mask', type: 'slider', min: 0, max: 5, step: 0.01, defaultValue: 0 },
      { id: 'highPass', label: 'High Pass', type: 'slider', min: 0, max: 20, step: 0.1, defaultValue: 0 },
      { id: 'edgeEnhance', label: 'Edge Enhance', type: 'slider', min: 0, max: 3, step: 0.01, defaultValue: 0 },
      { id: 'detailEnhance', label: 'Detail Enhance', type: 'slider', min: 0, max: 3, step: 0.01, defaultValue: 0 },
      { id: 'clarity', label: 'Clarity', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'localContrast', label: 'Local Contrast', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'distortion',
    label: 'Distortion',
    filters: [
      { id: 'bulge', label: 'Bulge', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'pinch', label: 'Pinch', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'twirl', label: 'Twirl', type: 'slider', min: -360, max: 360, step: 1, defaultValue: 0 },
      { id: 'wave', label: 'Wave', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'ripple', label: 'Ripple', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'zigzag', label: 'Zigzag', type: 'slider', min: 0, max: 50, step: 0.1, defaultValue: 0 },
      { id: 'turbulentDisplace', label: 'Turbulent Displace', type: 'slider', min: 0, max: 100, step: 0.5, defaultValue: 0 },
      { id: 'displacementMap', label: 'Displacement Map', type: 'slider', min: 0, max: 100, step: 0.5, defaultValue: 0 },
      { id: 'meshWarp', label: 'Mesh Warp', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'perspectiveWarp', label: 'Perspective Warp', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'lensDistortion', label: 'Lens Distortion', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'barrelDistortion', label: 'Barrel Distortion', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'pincushion', label: 'Pincushion', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'fisheye', label: 'Fisheye', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'spherize', label: 'Spherize', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'liquify', label: 'Liquify', type: 'slider', min: 0, max: 100, step: 0.5, defaultValue: 0 },
      { id: 'offset', label: 'Offset', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'polarCoordinates', label: 'Polar Coordinates', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'mirror', label: 'Mirror', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'kaleidoscope', label: 'Kaleidoscope', type: 'slider', min: 2, max: 32, step: 1, defaultValue: 6 },
    ],
  },
  {
    id: 'pixelation',
    label: 'Pixelation',
    filters: [
      { id: 'pixelate', label: 'Pixelate', type: 'slider', min: 1, max: 100, step: 1, defaultValue: 1 },
      { id: 'mosaic', label: 'Mosaic', type: 'slider', min: 1, max: 100, step: 1, defaultValue: 1 },
      { id: 'hexPixelate', label: 'Hexagonal Pixelate', type: 'slider', min: 1, max: 80, step: 1, defaultValue: 1 },
      { id: 'crystallize', label: 'Crystallize', type: 'slider', min: 1, max: 80, step: 1, defaultValue: 1 },
      { id: 'facet', label: 'Facet', type: 'slider', min: 1, max: 50, step: 1, defaultValue: 1 },
      { id: 'pointillize', label: 'Pointillize', type: 'slider', min: 1, max: 50, step: 1, defaultValue: 1 },
      { id: 'voronoi', label: 'Voronoi', type: 'slider', min: 1, max: 80, step: 1, defaultValue: 1 },
      { id: 'blockPixelation', label: 'Block Pixelation', type: 'slider', min: 1, max: 100, step: 1, defaultValue: 1 },
    ],
  },
  {
    id: 'noise',
    label: 'Noise',
    filters: [
      { id: 'addNoise', label: 'Add Noise', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'filmGrain', label: 'Film Grain', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'gaussianNoise', label: 'Gaussian Noise', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'saltAndPepper', label: 'Salt & Pepper', type: 'slider', min: 0, max: 0.5, step: 0.005, defaultValue: 0 },
      { id: 'perlinNoise', label: 'Perlin Noise Overlay', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'fractalNoise', label: 'Fractal Noise', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'dust', label: 'Dust', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'vhsNoise', label: 'VHS Noise', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'scanlineNoise', label: 'Scanline Noise', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'edgeDetection',
    label: 'Edge Detection',
    filters: [
      { id: 'sobel', label: 'Sobel', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'laplacian', label: 'Laplacian', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'canny', label: 'Canny', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'outline', label: 'Outline', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'findEdges', label: 'Find Edges', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'glowEdges', label: 'Glow Edges', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'emboss', label: 'Emboss', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'edgeDetectColor', label: 'Edge Detect Color', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'glowLighting',
    label: 'Glow & Lighting',
    filters: [
      { id: 'glow', label: 'Glow', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'innerGlow', label: 'Inner Glow', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'outerGlow', label: 'Outer Glow', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'bloom', label: 'Bloom', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'softGlow', label: 'Soft Glow', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'neonGlow', label: 'Neon Glow', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'lightRays', label: 'Light Rays', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'lightWrap', label: 'Light Wrap', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'lensFlare', label: 'Lens Flare', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'sunRays', label: 'Sun Rays', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'specularHighlight', label: 'Specular Highlight', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'artistic',
    label: 'Artistic',
    filters: [
      { id: 'oilPainting', label: 'Oil Painting', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'watercolor', label: 'Watercolor', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'pencilSketch', label: 'Pencil Sketch', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'ink', label: 'Ink', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'comic', label: 'Comic', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'cartoon', label: 'Cartoon', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'posterPaint', label: 'Poster Paint', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'chalk', label: 'Chalk', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'halftone', label: 'Halftone', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'crossHatch', label: 'Cross Hatch', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'woodcut', label: 'Woodcut', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'stainedGlass', label: 'Stained Glass', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'paintDaubs', label: 'Paint Daubs', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'geometry',
    label: 'Geometry',
    filters: [
      { id: 'rotate', label: 'Rotate', type: 'slider', min: -360, max: 360, step: 0.5, defaultValue: 0 },
      { id: 'flipH', label: 'Flip Horizontal', type: 'toggle', defaultValue: 0 },
      { id: 'flipV', label: 'Flip Vertical', type: 'toggle', defaultValue: 0 },
      { id: 'scale', label: 'Scale', type: 'slider', min: 0.1, max: 5, step: 0.01, defaultValue: 1 },
      { id: 'crop', label: 'Crop', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'perspective', label: 'Perspective', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'shear', label: 'Shear', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'skew', label: 'Skew', type: 'slider', min: -45, max: 45, step: 0.5, defaultValue: 0 },
      { id: 'affineTransform', label: 'Affine Transform', type: 'slider', min: -1, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'alphaTransparency',
    label: 'Alpha / Transparency',
    filters: [
      { id: 'opacity', label: 'Opacity', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 1 },
      { id: 'alphaThreshold', label: 'Alpha Threshold', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'chromaKey', label: 'Chroma Key', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'lumaKey', label: 'Luma Key', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'spillSuppression', label: 'Spill Suppression', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'matteExpansion', label: 'Matte Expansion', type: 'slider', min: -20, max: 20, step: 0.5, defaultValue: 0 },
      { id: 'matteShrink', label: 'Matte Shrink', type: 'slider', min: 0, max: 20, step: 0.5, defaultValue: 0 },
      { id: 'featherAlpha', label: 'Feather Alpha', type: 'slider', min: 0, max: 20, step: 0.5, defaultValue: 0 },
      { id: 'alphaBlur', label: 'Alpha Blur', type: 'slider', min: 0, max: 30, step: 0.5, defaultValue: 0 },
    ],
  },
  {
    id: 'channelOps',
    label: 'Channel Operations',
    filters: [
      { id: 'extractRed', label: 'Extract Red', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'extractGreen', label: 'Extract Green', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'extractBlue', label: 'Extract Blue', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'alphaOnly', label: 'Alpha Only', type: 'toggle', defaultValue: 0 },
      { id: 'swapChannels', label: 'Swap Channels', type: 'select', options: ['None', 'R↔G', 'R↔B', 'G↔B'], defaultValue: 0 },
      { id: 'rgbSplit', label: 'RGB Split', type: 'slider', min: 0, max: 50, step: 0.5, defaultValue: 0 },
      { id: 'channelOffset', label: 'Channel Offset', type: 'slider', min: -50, max: 50, step: 0.5, defaultValue: 0 },
      { id: 'channelBlur', label: 'Channel Blur', type: 'slider', min: 0, max: 30, step: 0.5, defaultValue: 0 },
    ],
  },
  {
    id: 'stylizedMotion',
    label: 'Stylized Motion Graphics',
    filters: [
      { id: 'rgbSplitMotion', label: 'RGB Split', type: 'slider', min: 0, max: 50, step: 0.5, defaultValue: 0 },
      { id: 'chromaticAberration', label: 'Chromatic Aberration', type: 'slider', min: 0, max: 30, step: 0.1, defaultValue: 0 },
      { id: 'vhs', label: 'VHS', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'crtMonitor', label: 'CRT Monitor', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'scanlines', label: 'Scanlines', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'digitalGlitch', label: 'Digital Glitch', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'pixelSorting', label: 'Pixel Sorting', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'datamosh', label: 'Datamosh Simulation', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'ghosting', label: 'Ghosting', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'echo', label: 'Echo', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'frameDelay', label: 'Frame Delay', type: 'slider', min: 0, max: 10, step: 1, defaultValue: 0 },
      { id: 'smear', label: 'Smear', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'trails', label: 'Trails', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'heatDistortion', label: 'Heat Distortion', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'refraction', label: 'Refraction', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'morphological',
    label: 'Morphological',
    filters: [
      { id: 'dilate', label: 'Dilate', type: 'slider', min: 0, max: 20, step: 0.5, defaultValue: 0 },
      { id: 'erode', label: 'Erode', type: 'slider', min: 0, max: 20, step: 0.5, defaultValue: 0 },
      { id: 'opening', label: 'Opening', type: 'slider', min: 0, max: 20, step: 0.5, defaultValue: 0 },
      { id: 'closing', label: 'Closing', type: 'slider', min: 0, max: 20, step: 0.5, defaultValue: 0 },
      { id: 'distanceTransform', label: 'Distance Transform', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
  {
    id: 'procedural',
    label: 'Procedural',
    filters: [
      { id: 'gradientFill', label: 'Gradient Fill', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'noiseFill', label: 'Noise Fill', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'patternFill', label: 'Pattern Fill', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'checkerboard', label: 'Checkerboard', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'dots', label: 'Dots', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'stripes', label: 'Stripes', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'voronoiPattern', label: 'Voronoi Pattern', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'cellularPattern', label: 'Cellular Pattern', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'plasma', label: 'Plasma', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
      { id: 'clouds', label: 'Clouds', type: 'slider', min: 0, max: 1, step: 0.01, defaultValue: 0 },
    ],
  },
];
