import type { EmitterConfig } from './types';
import { uid } from '../core/factory';

export function createEmitterConfig(overrides: Partial<EmitterConfig> = {}): EmitterConfig {
  return {
    id: uid(),
    name: 'Custom',
    maxParticles: 500,
    spawnRate: 60,
    burstCount: 0,
    burstRepeat: false,
    burstInterval: 1,
    emitterShape: 'point',
    emitterRadius: 20,
    emitterWidth: 100,
    emitterHeight: 100,
    initialSpeed: { min: 50, max: 150 },
    initialAngle: { min: 0, max: 360 },
    initialSize: { min: 4, max: 12 },
    initialRotation: { min: 0, max: 360 },
    lifetime: { min: 1, max: 3 },
    gravity: [0, 0],
    drag: 0.5,
    turbulenceStrength: 0,
    turbulenceScale: 0.01,
    spinSpeed: { min: 0, max: 0 },
    sizeOverLife: [1, 1, 0.8, 0.4, 0],
    opacityOverLife: [1, 1, 0.8, 0.3, 0],
    colorOverLife: [
      { t: 0, color: [1, 1, 1, 1] },
      { t: 1, color: [1, 1, 1, 0] },
    ],
    blendMode: 'alpha',
    spriteShape: 'circle',
    trailLength: 0,
    wind: [0, 0],
    attractor: null,
    ...overrides,
  };
}

export const PARTICLE_PRESETS: Record<string, () => EmitterConfig> = {
  fire: () => createEmitterConfig({
    name: 'Fire',
    maxParticles: 800,
    spawnRate: 120,
    burstCount: 0,
    emitterShape: 'circle',
    emitterRadius: 15,
    initialSpeed: { min: 60, max: 180 },
    initialAngle: { min: -110, max: -70 },
    initialSize: { min: 8, max: 28 },
    lifetime: { min: 0.4, max: 1.2 },
    gravity: [0, -80],
    drag: 1.2,
    turbulenceStrength: 120,
    turbulenceScale: 0.008,
    spinSpeed: { min: -2, max: 2 },
    sizeOverLife: [0.3, 1, 1.2, 0.8, 0],
    opacityOverLife: [0.8, 1, 0.9, 0.5, 0],
    colorOverLife: [
      { t: 0, color: [1, 0.95, 0.4, 1] },
      { t: 0.3, color: [1, 0.6, 0.1, 1] },
      { t: 0.7, color: [0.8, 0.2, 0.05, 0.8] },
      { t: 1, color: [0.2, 0.05, 0.02, 0] },
    ],
    blendMode: 'additive',
    spriteShape: 'smoke',
  }),

  smoke: () => createEmitterConfig({
    name: 'Smoke',
    maxParticles: 400,
    spawnRate: 40,
    emitterShape: 'circle',
    emitterRadius: 10,
    initialSpeed: { min: 20, max: 60 },
    initialAngle: { min: -120, max: -60 },
    initialSize: { min: 12, max: 40 },
    lifetime: { min: 2, max: 4 },
    gravity: [0, -30],
    drag: 0.8,
    turbulenceStrength: 60,
    turbulenceScale: 0.005,
    spinSpeed: { min: -0.5, max: 0.5 },
    sizeOverLife: [0.4, 0.8, 1, 1.3, 1.5],
    opacityOverLife: [0, 0.5, 0.6, 0.3, 0],
    colorOverLife: [
      { t: 0, color: [0.4, 0.4, 0.4, 0.8] },
      { t: 0.5, color: [0.5, 0.5, 0.5, 0.5] },
      { t: 1, color: [0.6, 0.6, 0.6, 0] },
    ],
    blendMode: 'alpha',
    spriteShape: 'smoke',
  }),

  confetti: () => createEmitterConfig({
    name: 'Confetti',
    maxParticles: 600,
    spawnRate: 0,
    burstCount: 200,
    burstRepeat: false,
    burstInterval: 0,
    emitterShape: 'rectangle',
    emitterWidth: 200,
    emitterHeight: 20,
    initialSpeed: { min: 100, max: 350 },
    initialAngle: { min: -130, max: -50 },
    initialSize: { min: 5, max: 12 },
    lifetime: { min: 2, max: 4 },
    gravity: [0, 200],
    drag: 1.5,
    turbulenceStrength: 80,
    turbulenceScale: 0.01,
    spinSpeed: { min: -8, max: 8 },
    sizeOverLife: [1, 1, 1, 0.8, 0.5],
    opacityOverLife: [1, 1, 1, 0.8, 0],
    colorOverLife: [
      { t: 0, color: [1, 0.2, 0.4, 1] },
      { t: 0.25, color: [0.2, 0.6, 1, 1] },
      { t: 0.5, color: [1, 0.9, 0.1, 1] },
      { t: 0.75, color: [0.3, 1, 0.5, 1] },
      { t: 1, color: [1, 0.4, 0.8, 0.5] },
    ],
    blendMode: 'alpha',
    spriteShape: 'square',
  }),

  sparks: () => createEmitterConfig({
    name: 'Sparks',
    maxParticles: 1000,
    spawnRate: 200,
    burstCount: 0,
    emitterShape: 'point',
    emitterRadius: 5,
    initialSpeed: { min: 150, max: 450 },
    initialAngle: { min: 0, max: 360 },
    initialSize: { min: 2, max: 6 },
    lifetime: { min: 0.3, max: 1 },
    gravity: [0, 300],
    drag: 0.5,
    turbulenceStrength: 40,
    turbulenceScale: 0.02,
    spinSpeed: { min: 0, max: 0 },
    sizeOverLife: [1, 0.8, 0.5, 0.2, 0],
    opacityOverLife: [1, 1, 0.8, 0.4, 0],
    colorOverLife: [
      { t: 0, color: [1, 1, 0.8, 1] },
      { t: 0.3, color: [1, 0.7, 0.2, 1] },
      { t: 1, color: [1, 0.3, 0.05, 0] },
    ],
    blendMode: 'additive',
    spriteShape: 'spark',
  }),

  snow: () => createEmitterConfig({
    name: 'Snow',
    maxParticles: 500,
    spawnRate: 40,
    burstCount: 0,
    emitterShape: 'rectangle',
    emitterWidth: 500,
    emitterHeight: 10,
    initialSpeed: { min: 20, max: 60 },
    initialAngle: { min: 70, max: 110 },
    initialSize: { min: 3, max: 8 },
    lifetime: { min: 4, max: 8 },
    gravity: [0, 20],
    drag: 2,
    turbulenceStrength: 30,
    turbulenceScale: 0.003,
    spinSpeed: { min: -1, max: 1 },
    sizeOverLife: [1, 1, 1, 1, 0.8],
    opacityOverLife: [0, 1, 1, 0.8, 0],
    colorOverLife: [
      { t: 0, color: [1, 1, 1, 1] },
      { t: 1, color: [0.9, 0.95, 1, 0.8] },
    ],
    blendMode: 'alpha',
    spriteShape: 'circle',
  }),

  magic: () => createEmitterConfig({
    name: 'Magic',
    maxParticles: 600,
    spawnRate: 80,
    burstCount: 0,
    emitterShape: 'ring',
    emitterRadius: 30,
    initialSpeed: { min: 10, max: 50 },
    initialAngle: { min: 0, max: 360 },
    initialSize: { min: 3, max: 10 },
    lifetime: { min: 1, max: 2.5 },
    gravity: [0, -20],
    drag: 1,
    turbulenceStrength: 50,
    turbulenceScale: 0.015,
    spinSpeed: { min: -3, max: 3 },
    sizeOverLife: [0, 1, 1.2, 0.8, 0],
    opacityOverLife: [0, 1, 1, 0.6, 0],
    colorOverLife: [
      { t: 0, color: [0.4, 0.6, 1, 1] },
      { t: 0.3, color: [0.8, 0.3, 1, 1] },
      { t: 0.7, color: [1, 0.5, 0.8, 0.8] },
      { t: 1, color: [0.6, 0.8, 1, 0] },
    ],
    blendMode: 'additive',
    spriteShape: 'star',
  }),

  rain: () => createEmitterConfig({
    name: 'Rain',
    maxParticles: 800,
    spawnRate: 150,
    burstCount: 0,
    emitterShape: 'rectangle',
    emitterWidth: 600,
    emitterHeight: 5,
    initialSpeed: { min: 300, max: 500 },
    initialAngle: { min: 85, max: 95 },
    initialSize: { min: 2, max: 4 },
    lifetime: { min: 0.8, max: 1.5 },
    gravity: [0, 400],
    drag: 0.2,
    turbulenceStrength: 10,
    turbulenceScale: 0.01,
    spinSpeed: { min: 0, max: 0 },
    sizeOverLife: [1, 1, 1, 1, 1],
    opacityOverLife: [0.3, 0.6, 0.6, 0.4, 0],
    colorOverLife: [
      { t: 0, color: [0.7, 0.8, 1, 0.6] },
      { t: 1, color: [0.5, 0.6, 0.9, 0.3] },
    ],
    blendMode: 'alpha',
    spriteShape: 'spark',
  }),

  bubbles: () => createEmitterConfig({
    name: 'Bubbles',
    maxParticles: 200,
    spawnRate: 15,
    burstCount: 0,
    emitterShape: 'rectangle',
    emitterWidth: 200,
    emitterHeight: 20,
    initialSpeed: { min: 20, max: 60 },
    initialAngle: { min: -110, max: -70 },
    initialSize: { min: 6, max: 20 },
    lifetime: { min: 3, max: 6 },
    gravity: [0, -40],
    drag: 1.5,
    turbulenceStrength: 40,
    turbulenceScale: 0.008,
    spinSpeed: { min: 0, max: 0 },
    sizeOverLife: [0.5, 1, 1, 1, 0],
    opacityOverLife: [0, 0.6, 0.5, 0.4, 0],
    colorOverLife: [
      { t: 0, color: [0.7, 0.9, 1, 0.5] },
      { t: 0.5, color: [0.8, 0.95, 1, 0.4] },
      { t: 1, color: [0.9, 1, 1, 0] },
    ],
    blendMode: 'alpha',
    spriteShape: 'circle',
  }),

  // ── B19 polish presets ──────────────────────────────────────────────────────────────────────
  dust: () => createEmitterConfig({
    name: 'Dust',
    maxParticles: 400, spawnRate: 45, emitterShape: 'rectangle', emitterWidth: 400, emitterHeight: 300,
    initialSpeed: { min: 4, max: 18 }, initialAngle: { min: 0, max: 360 }, initialSize: { min: 1, max: 3 },
    lifetime: { min: 4, max: 8 }, gravity: [0, -4], drag: 0.8, turbulenceStrength: 10, turbulenceScale: 0.01,
    wind: [8, 0], sizeOverLife: [0, 1, 1, 1, 0], opacityOverLife: [0, 0.35, 0.3, 0.2, 0],
    colorOverLife: [{ t: 0, color: [0.85, 0.82, 0.75, 0.4] }, { t: 1, color: [0.8, 0.78, 0.7, 0] }],
    blendMode: 'alpha', spriteShape: 'circle',
  }),
  embers: () => createEmitterConfig({
    name: 'Embers',
    maxParticles: 500, spawnRate: 70, emitterShape: 'rectangle', emitterWidth: 220, emitterHeight: 20,
    initialSpeed: { min: 30, max: 90 }, initialAngle: { min: 250, max: 290 }, initialSize: { min: 2, max: 5 },
    lifetime: { min: 1.2, max: 2.6 }, gravity: [0, -35], drag: 0.6, turbulenceStrength: 30, turbulenceScale: 0.02,
    wind: [12, 0], spinSpeed: { min: -2, max: 2 }, trailLength: 4,
    sizeOverLife: [0.6, 1, 0.8, 0.4, 0], opacityOverLife: [1, 1, 0.7, 0.3, 0],
    colorOverLife: [{ t: 0, color: [1, 0.95, 0.5, 1] }, { t: 0.5, color: [1, 0.5, 0.1, 1] }, { t: 1, color: [0.6, 0.1, 0.05, 0] }],
    blendMode: 'additive', spriteShape: 'spark',
  }),
  steam: () => createEmitterConfig({
    name: 'Steam',
    maxParticles: 250, spawnRate: 22, emitterShape: 'circle', emitterRadius: 20,
    initialSpeed: { min: 10, max: 30 }, initialAngle: { min: 250, max: 290 }, initialSize: { min: 24, max: 60 },
    lifetime: { min: 2.5, max: 5 }, gravity: [0, -22], drag: 1.2, turbulenceStrength: 14, turbulenceScale: 0.006,
    wind: [10, 0], sizeOverLife: [0.3, 0.7, 1, 1.2, 1.4], opacityOverLife: [0, 0.28, 0.22, 0.12, 0],
    colorOverLife: [{ t: 0, color: [0.95, 0.96, 0.98, 0.3] }, { t: 1, color: [0.9, 0.92, 0.95, 0] }],
    blendMode: 'screen', spriteShape: 'smoke',
  }),
  fireworks: () => createEmitterConfig({
    name: 'Fireworks',
    maxParticles: 400, spawnRate: 0, burstCount: 180, burstRepeat: true, burstInterval: 1.6,
    emitterShape: 'point', initialSpeed: { min: 140, max: 320 }, initialAngle: { min: 0, max: 360 },
    initialSize: { min: 2, max: 4 }, lifetime: { min: 1, max: 2.2 }, gravity: [0, 120], drag: 1.2,
    trailLength: 6, sizeOverLife: [1, 1, 0.8, 0.4, 0], opacityOverLife: [1, 1, 0.8, 0.4, 0],
    colorOverLife: [{ t: 0, color: [1, 0.9, 0.6, 1] }, { t: 0.4, color: [1, 0.3, 0.6, 1] }, { t: 1, color: [0.3, 0.2, 0.8, 0] }],
    blendMode: 'additive', spriteShape: 'spark',
  }),
  dissolve: () => createEmitterConfig({
    name: 'Dissolve',
    maxParticles: 800, spawnRate: 0, burstCount: 800, burstRepeat: false,
    emitterShape: 'rectangle', emitterWidth: 300, emitterHeight: 300,
    initialSpeed: { min: 10, max: 60 }, initialAngle: { min: 0, max: 360 }, initialSize: { min: 2, max: 5 },
    lifetime: { min: 1.5, max: 3 }, gravity: [0, -20], drag: 0.7, turbulenceStrength: 25, turbulenceScale: 0.02,
    wind: [15, 0], sizeOverLife: [1, 1, 0.7, 0.3, 0], opacityOverLife: [1, 1, 0.7, 0.3, 0],
    colorOverLife: [{ t: 0, color: [1, 1, 1, 1] }, { t: 1, color: [1, 1, 1, 0] }],
    blendMode: 'alpha', spriteShape: 'square',
  }),
};

export const PRESET_NAMES = Object.keys(PARTICLE_PRESETS) as (keyof typeof PARTICLE_PRESETS)[];
